spring:
  application:
    name: discovery-service

  cloud:
    loadbalancer:
      ribbon:
        enabled: false  


server:
  port: 8761

  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false