spring:
  application:
    name: discovery-service

  cloud:
    loadbalancer:
      ribbon:
        enabled: false  


server:
  port: 8761


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/